### PR TITLE
i don't know how i missed this

### PR DESCRIPTION
**Pull request by overestimate**
fixes `failed to verify that <account> can snipe: mj / ms acc: account is not authenticated` when attempting to authenticate over MS device code
p.s. why did you do the auth calls synchronously? that can mess up timings

### CODE REVIEW

**Comment by overestimate** [comment]
fixing errors gimme a moment

**Comment by Kqzz** [comment]
alr ping me when this is good to merge

**Comment by overestimate** [comment]
its good now @Kqzz
1d82c5a fixed it (do wait for goreleaser to check first)

**Comment by overestimate** [comment]
aaand it should work now

**Comment by overestimate** [comment]
@Kqzz sorry about the delay but it finally built

**Pull request merged**
