### PR TITLE
Add Autosnipe feature

### PR DESCRIPTION
**Pull request by suvan1911**
# Pull Request

## PR status

- [ ] Pull request changes made
- [ ] Code reviewed
- [ ] Code merged 

## Proposed changes

Added a CLI command 'autosnipe', which automatically gets the next 3 character name droptime, and snipes it for you.
## Related issues

No related issues.
## Notes from author

I am a beginner, I am sorry if I did something wrong.

### CODE REVIEW

**Comment by chrommie** [comment]
One of the only issues I see, it is relying on CKM

**Comment by Kqzz** [comment]
> One of the only issues I see, it is relying on CKM

Yeah i’ll consider adding this to star.shopping, but we’ll see.

**Comment by tenscape** [comment]
Why u format like dat

**Comment by Kqzz** [comment]
Looks good, but merging this and the logs pr will be a bit of work.

**Comment by overestimate** [comment]
> Looks good, but merging this and the logs pr will be a bit of work.

order should be
1. merge logs
2. catchup to main
3. edit logging to work correctly post-merge
4. commit logging fix

**Comment by Kqzz** [comment]
:+1:

**Comment by Kqzz** [comment]
> > Looks good, but merging this and the logs pr will be a bit of work.
> 
> order should be
> 
>     1. merge logs
> 
>     2. catchup to main
> 
>     3. edit logging to work correctly post-merge
> 
>     4. commit logging fix

done :)

**Pull request merged**
